In [21]:
import numpy as np
x = np.array(([2,9],[1,5],[3,6]),dtype=float) #Hours studied,Hours slept
y = np.array(([92],[89],[86]),dtype=float) #Marks scored
c=np.amax(x,axis=0)
print("Array Max : ",c)
x=x/c
y=y/100 #Test is out of 100 Marks
print(x)
print(y)

Array Max :  [3. 9.]
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.89]
 [0.86]]


In [23]:
def sigmoid(x): #Sigmoid Function #this function maps any value between 0 and 1
    return 1/(1 + np.exp(-x))
def sigmoid_grad(x): #Derivative of Sigmoid Function
    return x*(1-x)

In [25]:
#Variable initialization
epoch = 1000 #Setting training iterations
eta = 0.1 #Setting learning Rate
input_neurons = 2 #number of features in dataset
hidden_neurons = 3 #number of hidden layer neurons
output_neurons = 1 #number of output layer neurons

In [27]:
#Weight and Bias initializations
wh = np.random.uniform(size=(input_neurons,hidden_neurons)) #2,3
print(wh)
bh = np.random.uniform(size=(1,hidden_neurons)) #1,3
print(bh) #bias matrix to the hidden layer
wout = np.random.uniform(size=(hidden_neurons,output_neurons)) #3,1
print(wout) #weight matrix to output layer
bout = np.random.uniform(size=(1,output_neurons)) #1,1
print(bout) #Bias Matrix to the output layer

[[0.70038302 0.32939857 0.75290751]
 [0.68158537 0.44152593 0.179174  ]]
[[0.75819999 0.4546805  0.89344409]]
[[0.66268422]
 [0.76598604]
 [0.42394659]]
[[0.21530766]]


In [34]:
for i in range(epoch):
    #Forward Propagation
    h_ip = np.dot(x,wh)+bh #Bias Hidden Gradient Descent
    #print(h_ip)
    h_act = sigmoid(h_ip) #Hidden layer activation
    o_ip = np.dot(h_act,wout)+bout
    #print(o_ip)
    output = sigmoid(o_ip)

In [39]:
#Backward Propagation
#error at output layer
Eo = y-output #compare prediction with actual output and calculate the gradient of error(Actual - Predicted)
outgrad = sigmoid_grad(output) #Compute the slope/ gradient of hidden and output layer neurons
d_output = Eo*outgrad #Compute change factor(delta) at output layer, dependent on the gradient of error multiplied by the slope of output layer activation
print("Delta(Change Factor) at output layer is ",d_output)

Delta(Change Factor) at output layer is  [[0.00924751]
 [0.00803037]
 [0.00141787]]


In [40]:
#error at hidden layer
Eh = d_output.dot(wout.T) #At this step, the error will propagate back into the network which means error at hidden layer. we will take the dot product of output layer delta with weight parameters of edges between the hidden and output layer (wout.T).
hiddengrad = sigmoid_grad(h_act) #how much hidden layer weight contributed to error
d_hidden = Eh*hiddengrad

In [41]:
wout += h_act.T.dot(d_output)*eta
wh += x.T.dot(d_hidden)*eta

In [45]:
print("Normalized input : \n",str(x))
print("Actual output : \n",str(y))
print("Predicted output : \n",output)

Normalized input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output : 
 [[0.92]
 [0.89]
 [0.86]]
Predicted output : 
 [[0.84818449]
 [0.83243047]
 [0.84894346]]
